spring:
  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

springdoc:
  api-docs:
    path: /api-docs

token:
  signing:
    key: ${KEY}

email:
  sender:  ${EMAIL_SENDER}
  password: ${EMAIL_PASSWORD}


server:
  servlet:
    context-path: "/smt"